//preamble.glsl
#define POSITION_ATTRIB_LOCATION 0
#define COLOR_ATTRIB_LOCATION 1
#define TEXTURE_COORD_ATTRIB_LOCATION 2
#define CAMERA_MATRIX_ATTRIB_LOCATION 0
#define TEXTURE_UNIFORM_LOCATION 1
#define TEXT_COLOR_UNIFORM_LOCATION 2
#define WORLD_MATRIX_ATTRIB_LOCATION 3
#define CURRENT_FRAME_LOCATION 4
#define TOTAL_FRAMES_LOCATION 5